---
- name: 2.1.1 | Ensure time synchronization is in use
  tags: 
    - rule_2.1.1
  block:
  # Time synchronization daemon is systemd-timesyncd
  - name: 2.1.1.1 | Ensure a single time synchronization daemon is in use
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_2.1.1.1
    ansible.builtin.package:
      name: 
        - ntp
        - chrony
      state: absent

# 2.1.2 Configure chrony, omit

- name: 2.1.3 | Configure systemd-timesyncd
  tags: 
    - rule_2.1.3
  block:
   # 2.1.3.1 Manual, omit
  - name: 2.1.3.2 | Ensure systemd-timesyncd is enabled and running
    tags: 
      - lvl1-server
      - lvl1-workstation
      - rule_2.1.3.2
    block:
    - name: 2.1.3.2 | REMEDIATION | Ensure systemd-timesyncd is installed
      ansible.builtin.package:
        name: systemd-timesyncd
        state: present
    - name: 2.1.3.2 | REMEDIATION | Ensure systemd-timesyncd is enabled and running
      ansible.builtin.systemd:
        name: systemd-timesyncd
        enabled: true
        state: started
        masked: no

# 2.1.4 Configure ntp, omit