---
- name: 4.2.1 | Configure journald
  tags:
    - rule_4.2.1
  block:
  - name: 4.2.1.1.1 | Ensure systemd-journal-remote is installed
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.1.1.1
    ansible.builtin.package:
      name: systemd-journal-remote
      state: present
  # 4.2.1.1.2 Manual, omit
  # 4.2.1.1.3 Manual, omit
  - name: 4.2.1.1.4 | Ensure journald is not configured to recieve logs from a remote client 
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.1.1.4
    ansible.builtin.systemd_service:
        name: systemd-journal-remote.socket
        enabled: no
        state: stopped
  # 4.2.1.2 Audited, omit
  - name: 4.2.1.3 | Ensure journald is configured to compress large log files
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.1.3
    ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#\\s*Compress=|^Compress="
      line: "Compress={{ journald_vars.compress }}"
  - name: 4.2.1.4 | Ensure journald is configured to write logfiles to persistent disk
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.1.4
    ansible.builtin.lineinfile:
      path: /etc/systemd/journald.conf
      regexp: "^#\\s*Storage=|^Storage="
      line: "Storage={{ journald_vars.storage }}"
  # 4.2.1.5 Manual, omit
  # 4.2.1.6 Manual, omit
  # 4.2.1.7 Manual, omit

- name: 4.2.2 | Configure rsyslog
  tags:
    - rule_4.2.2
  block:
  - name: 4.2.2.1 | Ensure rsyslog is installed
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.2.1
    ansible.builtin.package:
      name: rsyslog
      state: present
  - name: 4.2.2.2 | Ensure rsyslog service is enabled
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.2.2
    ansible.builtin.systemd_service:
        name: rsyslog
        enabled: yes
        state: started
  # 4.2.2.3 Manual, omit
  - name: 4.2.2.4 | Ensure rsyslog default file permissions are configured
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.2.4
    ansible.builtin.lineinfile:
      path: /etc/rsyslog.conf
      regexp: "^#\\s*$FileCreateMode\\s*|^$FileCreateMode\\s*"
      line: "$FileCreateMode {{ rsyslog_vars.file_create_mode }}"

  # 4.2.2.5 Manual, omit
  # 4.2.2.6 Manual, omit
  - name: 4.2.2.4 | MAIN | Ensure rsyslog default file permissions are configured
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_4.2.2.4
    block:
    - name: 4.2.2.4 | REMEDIATION | Enable imtcp module rsyslog
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^#\s*module\(load="imtcp"\)'
        line: 'module(load="imtcp")'
    - name: 4.2.2.4 | REMEDIATION | Enable rsyslog port
      ansible.builtin.lineinfile:
        path: /etc/rsyslog.conf
        regexp: '^#\s*input(type="imtcp" port="514")'
        line: 'input(type="imtcp" port="514")'
  
  - name: Restart rsyslog
    ansible.builtin.systemd_service:
        name: rsyslog
        state: restarted
# 4.2.3 Omit