---
- name: 5.1.1 | Ensure cron daemon is enabled and running
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.1
  ansible.builtin.systemd_service:
    name: cron
    enabled: true
    state: started
  