---
# defaults file for vagrant-cis-hardening

# Templates variables
temp_vars:
  uid_min: 1000

# Section 4 variables
journald_vars:
  compress: "yes"
  storage: "persistent"
rsyslog_vars:
  file_create_mode: "0640"

# Section 5 variables
auditd_vars:
  max_log_file: 12
  max_log_file_action: "keep_logs"
  space_left_action: email
  action_mail_acct: root
  admin_space_left_action: single
sshd_vars:
  allowusers: vagrant
  allowgroups: vagrant
  denyusers: root
  denygroups: root
  loglevel: INFO
  usepam: "yes"
  permitrootlogin: "no"
  hostbasedauthentication: "no"
  permitemptypasswords: "no"
  permituserenvironment: "no"
  ignorerhosts: "no"
  x11forwarding: "no"
  ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  macs: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
  kexalgorithms: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
  allowtcpforwarding: "no"
  banner_path: /etc/issue.net
  maxauthtries: 4
  maxstartups: 10:30:60
  maxsessions: 10
  logingracetime: 60
  clientaliveinterval: 15
  clientalivecountmax: 3
sudoers_vars:
  logfilepath: "/var/log/sudo.log"
  timestamptimeout: 15
pam_vars:
  minlen: 12
  minclass: 4
  deny: 4
  fail_interval: 900
  unlock_time: 600
  encrypt_method: yescrypt
  login_defs_umask: "027"
  login_defs_usergroup_enab: "no"
accenv_vars:
  passmindays: 1
  passmaxdays: 365
  passwarnage: 7
  inactive: 30