---
- name: "3.1 | Disable unused network protocols and devices"
  include_tasks: 3.1.yml

- name: "3.2 | Network Parameters (Host Only)"
  include_tasks: 3.2.yml

- name: "3.3 | Network Parameters (Host and Router)"
  include_tasks: 3.3.yml

- name: "3.5 | Firewall Configuration"
  include_tasks: 3.5.yml