---
# defaults file for vagrant-cis-hardening

# Section 5 variables
sshd_vars:
  allowusers: vagrant
  allowgroups: vagrant
  denyusers: root
  denygroups: root
  loglevel: INFO
  usepam: "yes"
  permitrootlogin: "no"
  hostbasedauthentication: "no"
  permitemptypasswords: "no"
  permituserenvironment: "no"
  ignorerhosts: "no"
  x11forwarding: "no"
  ciphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  macs: hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256
  kexalgorithms: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
  allowtcpforwarding: "no"
  banner_path: /etc/issue.net
  maxauthtries: 4
  maxstartups: 10:30:60
  maxsessions: 10
  logingracetime: 60
  clientaliveinterval: 15
  clientalivecountmax: 3