---
- name: 1.3.1 | Ensure AIDE is installed
  tags: 
    - lvl1-server
    - lvl1-workstation
    - rule_1.3.1
  block:
    - name: 1.3.1 | Install AIDE
      ansible.builtin.package:
        name: 
          - aide
          - aide-common
        state: present
    - name: 1.3.1 | Initialize AIDE
      ansible.builtin.shell: |
        aideinit
        mv /var/lib/aide/aide.db.new /var/lib/aide/aide.db

# - name: 1.3.2 | Ensure filesystem integrity is regularly checked
#   tags: 
#     - lvl1-server
#     - lvl1-workstation
#     - rule_1.3.2