---
- name: 1.6.1 | Configure AppArmor
  tags: 
    - rule_1.6.1
  block:
  - name: 1.6.1.1 | Ensure AppArmor is installed
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_1.6.1.1
    ansible.builtin.package:
      name: 
        - apparmor
        - apparmor-utils
      state: present
  - name: 1.6.1.2 | Ensure AppArmor is enabled in bootloader configuration
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_1.6.1.2
    block:
      - name: 1.6.1.2 | REMEDIATION | Add apparmor and security parameters to /etc/default/grub file
        ansible.builtin.lineinfile:
          path: /etc/default/grub
          regexp: '^GRUB_CMDLINE_LINUX='
          line: 'GRUB_CMDLINE_LINUX="apparmor=1 security=apparmor"'
          backup: true
      - name: 1.6.1.2 | REMEDIATION | Update grub
        ansible.builtin.shell:
          cmd: update-grub
  - name: 1.6.1.3 | Ensure all AppArmor Profiles are in enforce or complain mode
    tags:
      - lvl1-server
      - lvl1-workstation
      - rule_1.6.1.3
    ansible.builtin.shell:
      cmd: aa-enforce /etc/apparmor.d/*
  
  # 1.6.1.4 Already set to enforce mode, omit