---
- name: 5.1.1 | Ensure cron daemon is enabled and running
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.1
  ansible.builtin.systemd_service:
    name: cron
    enabled: true
    state: started

- name: 5.1.2 | Ensure permissions on /etc/crontab are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.2
  ansible.builtin.file:
    path: /etc/crontab
    mode: 0600
    owner: root
    group: root

- name: 5.1.3 | Ensure permissions on /etc/cron.hourly are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.3
  ansible.builtin.file:
    path: /etc/cron.hourly
    mode: 0700
    owner: root
    group: root
    state: directory

- name: 5.1.4 | Ensure permissions on /etc/cron.daily are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.4
  ansible.builtin.file:
    path: /etc/cron.daily
    mode: 0700
    owner: root
    group: root
    state: directory

- name: 5.1.5 | Ensure permissions on /etc/cron.weekly are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.5
  ansible.builtin.file:
    path: /etc/cron.weekly
    mode: 0700
    owner: root
    group: root
    state: directory

- name: 5.1.6 | Ensure permissions on /etc/cron.monthly are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.6
  ansible.builtin.file:
    path: /etc/cron.monthly
    mode: 0700
    owner: root
    group: root
    state: directory

- name: 5.1.7 | Ensure permissions on /etc/cron.d are configured
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.7
  ansible.builtin.file:
    path: /etc/cron.monthly
    mode: 0700
    owner: root
    group: root
    state: directory

- name: 5.1.8 | MAIN | Ensure cron is restricted to authorized users
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.8
  block:
    - name: 5.1.8 | REMEDIATION | Remove cron.deny
      ansible.builtin.file:
        path: /etc/cron.deny
        state: absent
    - name: 5.1.8 | AUDIT | Check if cron.allow exists
      ansible.builtin.stat:
        path: /etc/cron.allow
      register: cron_allow_state
    - name: 5.1.8 | REMEDIATION | Create cron.allow
      ansible.builtin.file:
        path: /etc/cron.allow
        mode: 0640
        owner: root
        group: root
        state: '{{ "file" if cron_allow_state.stat.exists else "touch" }}'

- name: 5.1.9 | MAIN | Ensure at is restricted to authorized users
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.1.9
  block:
    - name: 5.1.9 | REMEDIATION | Remove at.deny
      ansible.builtin.file:
        path: /etc/at.deny
        state: absent
    - name: 5.1.9 | AUDIT | Check if at.allow exists
      ansible.builtin.stat:
        path: /etc/at.allow
      register: at_allow_state
    - name: 5.1.9 | REMEDIATION | Create cron.allow
      ansible.builtin.file:
        path: /etc/at.allow
        mode: 0640
        owner: root
        group: root
        state: '{{ "file" if at_allow_state.stat.exists else "touch" }}'