---
- name: 5.3.1 | Ensure sudo is installed
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.1
  ansible.builtin.package:
    name: sudo
    state: present

- name: 5.3.2 | Ensure sudo commands use pty
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.2
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^#\\s*Defaults\\s*use_pty|^Defaults\\s*use_pty"
    line: "Defaults        use_pty"
    validate: "visudo -cf %s"

- name: 5.3.3 | Ensure sudo log file exists
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.3
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^#\\s*Defaults\\s*logfile=|^Defaults\\s*logfile="
    line: "Defaults        logfile={{ sudoers_vars.logfilepath }}"
    validate: "visudo -cf %s"

# 5.3.4 - No root password in our configuration, omit

- name: 5.3.5 | Ensure re-authentication for privilege escalation is not disabled globally
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.5
  block:
  - name: 5.3.5 | AUDIT | Find sudoers files
    ansible.builtin.shell:
      cmd: "find /etc/sudoers* -type f"
    register: sudoers_files
  - name: 5.3.5 | REMEDIATION | Remove occurrences of !authenticate
    ansible.builtin.replace:
        path: "{{ item }}"
        regexp: "!authenticate"
        replace: ''
        validate: "/usr/sbin/visudo -cf %s"
    loop: "{{ sudoers_files.stdout_lines }}"

- name: 5.3.6 | Ensure sudo authentication timeout is configured correctly
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.6
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^#\\s*Defaults\\s*timestamp_timeout=|^Defaults\\s*timestamp_timeout="
    line: "Defaults        timestamp_timeout={{ sudoers_vars.timestamptimeout }}"
    validate: "visudo -cf %s"

- name: 5.3.7 | MAIN | Ensure access to the su command is restricted
  tags:
    - lvl1-server
    - lvl1-workstation
    - rule_5.3.7
  block:
  - name: 5.4.3 | REMEDIATION | Setting PAM su config from template
    ansible.builtin.template:
      src: su.j2
      dest: /etc/pam.d/su