---
- name: Install postfix on Mail server VM
  hosts: mailservers
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
  roles:
    - postfix