---
- name: Install XFCE4 on Developer VM
  hosts: devservers
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
  tasks:
    - name: Install XFCE4 package
      package:
        name: xfce4
        state: present