---
- name: Install tomcat on First App VM
  hosts: tomcatservers
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400
  roles:
    - tomcat