---
- name: Install jenkins on Second App VM
  hosts: jenkinsservers
  gather_facts: true
  become: true
  pre_tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 86400
    - name: Install Java 11
      package:
        name: openjdk-11-jdk
        state: present
  roles:
    - jenkins